version: '3'
services:
  cassandra0:
    image: cassandra:3
    container_name: cassandra0
    ports:
     - 9042:9042
     - 7199:7199
networks:
    default:
        external:
          name: some-net
